name = "mirageatlas-com"
main = "src/worker.ts"
compatibility_date = "2025-04-01"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "404-page"
run_worker_first = true

[[kv_namespaces]]
binding = "WAITLIST"
id = "4e63a861d429488d84288d59192c2d53"
preview_id = "5ca12211dcca434082eede39c8e4440b"
